import type { DemoAuction } from "@/components/marketing/AuctionCard";

const countryMap: Record<string, { name: string }> = {
  benin: { name: "Bénin" },
  togo: { name: "Togo" },
  ghana: { name: "Ghana" },
  nigeria: { name: "Nigeria" },
  cote_ivoire: { name: "Côte d'Ivoire" },
  senegal: { name: "Sénégal" },
  burkina_faso: { name: "Burkina Faso" },
};

const categoryMap: Record<string, { name: string }> = {
  vehicules: { name: "Véhicules" },
  immobilier: { name: "Immobilier" },
  bijoux: { name: "Bijoux / Or" },
  art: { name: "Art / Antiquités" },
  electronique: { name: "Électronique" },
  meubles: { name: "Meubles" },
  machines: { name: "Machines" },
  autres: { name: "Autres" },
};

const rawAuctions = [
  {
    id: "1",
    title: "Toyota Camry 2020",
    description:
      "Véhicule Toyota Camry année 2020, saisi par la douane béninoise. Bon état général, révision à jour.",
    images: [],
    startingPrice: 8000000,
    currentPrice: 12500000,
    currency: "XOF",
    category: "vehicules",
    country: "benin",
    type: "judiciaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-20",
    liveTime: "14h00",
    sellerName: "Douane Béninoise",
    condition: "Bon état",
    location: "Cotonou",
  },
  {
    id: "2",
    title: "Appartement F3 - Cocody",
    description: "Appartement F3 situé à Cocody, appartement de luxe avec vue sur mer. 120m².",
    images: [],
    startingPrice: 45000000,
    currentPrice: 52000000,
    currency: "XOF",
    category: "immobilier",
    country: "cote_ivoire",
    type: "judiciaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-22",
    liveTime: "10h00",
    sellerName: "Justice Côte d'Ivoire",
    condition: "Excellent",
    location: "Cocody, Abidjan",
  },
  {
    id: "3",
    title: "Parure bijoux or 18k",
    description:
      "Parure complète en or 18 carats avec bracelets, boucles d'oreilles et collier.",
    images: [],
    startingPrice: 2500000,
    currentPrice: 3800000,
    currency: "XOF",
    category: "bijoux",
    country: "togo",
    type: "volontaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-19",
    liveTime: "15h00",
    sellerName: "Particulier",
    condition: "Neuf",
    location: "Lomé",
  },
  {
    id: "4",
    title: "Camion Mercedes Benz",
    description: "Camion benne Mercedes Benz, année 2018, saisi par les autorités ghanaéennes.",
    images: [],
    startingPrice: 15000000,
    currentPrice: 18500000,
    currency: "XOF",
    category: "vehicules",
    country: "ghana",
    type: "judiciaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-21",
    liveTime: "09h00",
    sellerName: "Customs Ghana",
    condition: "Bon état",
    location: "Accra",
  },
  {
    id: "5",
    title: "Ordinateurs Dell - Lot 20",
    description: "Lot de 20 ordinateurs portables Dell Latitude E5470.",
    images: [],
    startingPrice: 3500000,
    currentPrice: 4200000,
    currency: "XOF",
    category: "electronique",
    country: "nigeria",
    type: "judiciaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-23",
    liveTime: "11h00",
    sellerName: "Nigeria Customs",
    condition: "Occasion",
    location: "Lagos",
  },
  {
    id: "6",
    title: "Tableau peinture africaine",
    description: "Tableau Oil on Canvas par artiste local. 120x80cm.",
    images: [],
    startingPrice: 800000,
    currentPrice: 1200000,
    currency: "XOF",
    category: "art",
    country: "senegal",
    type: "volontaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-24",
    liveTime: "16h00",
    sellerName: "Galerie Dakar",
    condition: "Neuf",
    location: "Dakar",
  },
  {
    id: "7",
    title: "Groupe électrogène 50kVA",
    description: "Groupe électrogène diesel 50kVA, parfait pour usage industriel.",
    images: [],
    startingPrice: 8000000,
    currentPrice: 8000000,
    currency: "XOF",
    category: "machines",
    country: "burkina_faso",
    type: "judiciaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-25",
    liveTime: "08h00",
    sellerName: "Justice BF",
    condition: "Bon état",
    location: "Ouagadougou",
  },
  {
    id: "8",
    title: "Canapé cuir salon",
    description: "Canapé cuir 3 places + 2 fauteuils assortis, couleur cognac.",
    images: [],
    startingPrice: 1200000,
    currentPrice: 1200000,
    currency: "XOF",
    category: "meubles",
    country: "togo",
    type: "volontaire" as const,
    status: "active" as const,
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    scheduleDate: "2024-04-26",
    liveTime: "14h00",
    sellerName: "Meuble Plus",
    condition: "Très bon état",
    location: "Lomé",
  },
];

export const demoAuctions: DemoAuction[] = rawAuctions.map((a) => {
  const category = categoryMap[a.category] ?? categoryMap["autres"];
  const country = countryMap[a.country] ?? { name: a.country };
  return {
    ...a,
    category: category.name,
    categoryKey: a.category,
    country: country.name,
    countryKey: a.country,
  };
});

export function getActiveAuctions(limit = 6): DemoAuction[] {
  return demoAuctions
    .filter((a) => a.status === "active")
    .sort((a, b) => new Date(a.endDate).getTime() - new Date(b.endDate).getTime())
    .slice(0, limit);
}

export function getAuctionById(id: string): DemoAuction | undefined {
  return demoAuctions.find((a) => a.id === id);
}
